server:
  port: 9001
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testDb
  jpa:
    defer-datasource-initialization: true

logging:
  level:
    org.learning: DEBUG

